from __future__ import annotations

from string import Template

PAGE_BACKGROUND = "#181818"
SURFACE_BACKGROUND = "#2a2a2a"
TEXT_PRIMARY = "#ffffff"
TEXT_MUTED = "#8b8b8b"

PLAN_MODE = TEXT_MUTED
BUILD_MODE = TEXT_PRIMARY
APPROVE_FOR_ME = "#7bbefd"
FULL_ACCESS = "#fe8549"

INFO_BAR_BACKGROUND = "#1e1e1e"
OVERLAY_BACKGROUND = "rgba(0, 0, 0, 0.6)"

DIFF_ADD_BG = "#1e3a1e"
DIFF_ADD_FG = "#7fd97f"
DIFF_DEL_BG = "#3a1e1e"
DIFF_DEL_FG = "#d97f7f"


def render_css(template: str) -> str:
    return Template(template).substitute(
        PAGE_BACKGROUND=PAGE_BACKGROUND,
        SURFACE_BACKGROUND=SURFACE_BACKGROUND,
        TEXT_PRIMARY=TEXT_PRIMARY,
        TEXT_MUTED=TEXT_MUTED,
        PLAN_MODE=PLAN_MODE,
        BUILD_MODE=BUILD_MODE,
        APPROVE_FOR_ME=APPROVE_FOR_ME,
        FULL_ACCESS=FULL_ACCESS,
        INFO_BAR_BACKGROUND=INFO_BAR_BACKGROUND,
        OVERLAY_BACKGROUND=OVERLAY_BACKGROUND,
        DIFF_ADD_BG=DIFF_ADD_BG,
        DIFF_ADD_FG=DIFF_ADD_FG,
        DIFF_DEL_BG=DIFF_DEL_BG,
        DIFF_DEL_FG=DIFF_DEL_FG,
    )
